import idaapi
import idautils
import idc
import ida_typeinf
import ida_bytes
import os
import json

class IDBExporter:
    def __init__(self, output_path, config_path=None):
        self.output_path = output_path
        self.lines = []
        self.config = self._load_config(config_path)

    def _load_config(self, config_path):
        default_config = {
            "export_rename_functions": True,
            "export_comments": True,
            "export_data_strings": True,
            "export_segments": True,
            "export_structures": True,
            "export_enums": True,
            "export_types": True,
            "export_flags": True,
            "export_patched_bytes": True,
        }
        if config_path and os.path.exists(config_path):
            try:
                with open(config_path, 'r', encoding='utf-8') as f:
                    user_config = json.load(f)
                for key in default_config:
                    if key in user_config:
                        default_config[key] = bool(user_config[key])
                print("[+] Loaded config from: {}".format(config_path))
            except Exception as e:
                print("[-] Failed to load config: {}. Using defaults.".format(e))
        return default_config

    def emit(self, line=""):
        self.lines.append(line)

    def export(self):
        self.emit('#!/usr/bin/env python3')
        self.emit('"""')
        self.emit('Auto-generated IDAPython script from IDA database')
        self.emit('Original file: {}'.format(idc.get_input_file_path()))
        self.emit('IDA Version: {}'.format(idaapi.get_kernel_version()))
        self.emit('Generated by IDB Exporter')
        self.emit('"""')
        self.emit('')
        self.emit('import idaapi')
        self.emit('import idautils')
        self.emit('import idc')
        self.emit('')
        self.emit('')
        self.emit('def apply_analysis():')
        self.emit('    """Apply all exported analysis to the current database."""')
        self.emit('    print("[*] Applying exported analysis...")')
        self.emit('')
        if self.config.get("export_rename_functions", True):
            self.export_rename_functions()
        if self.config.get("export_comments", True):
            self.export_comments()
        if self.config.get("export_data_strings", True):
            self.export_data_strings()
        if self.config.get("export_segments", True):
            self.export_segments()
        if self.config.get("export_structures", True):
            self.export_structures()
        if self.config.get("export_enums", True):
            self.export_enums()
        if self.config.get("export_types", True):
            self.export_types()
        if self.config.get("export_flags", True):
            self.export_flags()
        if self.config.get("export_patched_bytes", True):
            self.export_patched_bytes()
        self.emit('')
        self.emit('    print("[+] Analysis applied successfully!")')
        self.emit('')
        self.emit('')
        self.emit('if __name__ == "__main__":')
        self.emit('    apply_analysis()')
        with open(self.output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(self.lines))
        print("[+] Exported to: {}".format(self.output_path))

    def export_rename_functions(self):
        self.emit('    # === Function Names ===')
        self.emit('    print("[*] Applying function names...")')
        count = 0
        for ea in idautils.Functions():
            name = idc.get_func_name(ea)
            if name and not name.startswith('sub_') and not name.startswith('nullsub_') and not name.startswith('locret_'):
                self.emit('    idc.set_name(0x{:X}, "{}", idc.SN_NOWARN)'.format(ea, name))
                count += 1
        self.emit('    print("[+] Applied {} function names")'.format(count))
        self.emit('')

    def export_comments(self):
        self.emit('    # === Comments ===')
        self.emit('    print("[*] Applying comments...")')
        regular_count = 0
        repeatable_count = 0
        for seg_ea in idautils.Segments():
            for ea in idautils.Heads(seg_ea, idc.get_segm_end(seg_ea)):
                comment = idc.get_cmt(ea, 0)
                if comment:
                    escaped = comment.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
                    self.emit('    idc.set_cmt(0x{:X}, "{}", 0)'.format(ea, escaped))
                    regular_count += 1
                repeatable = idc.get_cmt(ea, 1)
                if repeatable:
                    escaped = repeatable.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
                    self.emit('    idc.set_cmt(0x{:X}, "{}", 1)'.format(ea, escaped))
                    repeatable_count += 1
        self.emit('    print("[+] Applied {} regular comments, {} repeatable comments")'.format(regular_count, repeatable_count))
        self.emit('')

    def export_data_strings(self):
        self.emit('    # === String Names ===')
        self.emit('    print("[*] Applying string names...")')
        count = 0
        for seg_ea in idautils.Segments():
            seg = idaapi.getseg(seg_ea)
            if seg:
                for ea in idautils.Heads(seg_ea, idc.get_segm_end(seg_ea)):
                    if idc.get_str_type(ea) is not None:
                        name = idc.get_name(ea)
                        if name and not name.startswith('a') and not name.startswith('unk_'):
                            escaped = name.replace('\\', '\\\\').replace('"', '\\"')
                            self.emit('    idc.set_name(0x{:X}, "{}", idc.SN_NOWARN)'.format(ea, escaped))
                            count += 1
        self.emit('    print("[+] Applied {} string names")'.format(count))
        self.emit('')

    def export_segments(self):
        self.emit('    # === Segment Properties ===')
        self.emit('    print("[*] Applying segment properties...")')
        for seg_ea in idautils.Segments():
            seg = idaapi.getseg(seg_ea)
            if seg:
                name = idaapi.get_segm_name(seg)
                sclass = seg.sclass
                self.emit('    seg = idaapi.get_segm_by_name("{}")'.format(name))
                self.emit('    if seg:')
                self.emit('        seg.sclass = {}'.format(sclass))
                self.emit('        idaapi.update_segm(seg)')
        self.emit('    print("[+] Applied segment properties")')
        self.emit('')

    def export_structures(self):
        self.emit('    # === Structures ===')
        self.emit('    print("[*] Applying structures...")')
        til = ida_typeinf.get_idati()
        ordinal_count = ida_typeinf.get_ordinal_count(til)
        for ordinal in range(1, ordinal_count + 1):
            tif = ida_typeinf.tinfo_t()
            if tif.get_numbered_type(til, ordinal):
                if tif.is_udt():
                    name = tif.get_type_name()
                    if name:
                        self.emit('    # Structure: {}'.format(name))
                        self.emit('    try:')
                        self.emit('        sid = idc.get_struc_id("{}")'.format(name))
                        self.emit('        if sid == idc.BADADDR:')
                        self.emit('            sid = idc.add_struc(-1, "{}")'.format(name))
                        self.emit('            idc.SetLocalType(-1, """{}""", 0)'.format(name))
                        udt = ida_typeinf.udt_type_data_t()
                        if tif.get_udt_details(udt):
                            for udm in udt:
                                m_name = udm.name
                                m_offset = udm.offset // 8
                                m_size = udm.size // 8
                                self.emit('        idc.add_struc_member(sid, "{}", 0x{:X}, idaapi.FF_DATA | idaapi.FF_BYTE, -1, 0x{:X})'.format(
                                    m_name.replace('\\', '\\\\').replace('"', '\\"'),
                                    m_offset, m_size))
                        self.emit('    except Exception as e:')
                        self.emit('        print("[-] Error creating structure {}: {{}}".format(e))'.format(name))
                        self.emit('')
        self.emit('    print("[+] Applied structures")')
        self.emit('')

    def export_enums(self):
        self.emit('    # === Enums ===')
        self.emit('    print("[*] Applying enums...")')
        til = ida_typeinf.get_idati()
        ordinal_count = ida_typeinf.get_ordinal_count(til)
        for ordinal in range(1, ordinal_count + 1):
            tif = ida_typeinf.tinfo_t()
            if tif.get_numbered_type(til, ordinal):
                if tif.is_enum():
                    name = tif.get_type_name()
                    if name:
                        self.emit('    # Enum: {}'.format(name))
                        self.emit('    try:')
                        self.emit('        eid = idc.get_enum("{}")'.format(name))
                        self.emit('        if eid == idc.BADADDR:')
                        self.emit('            eid = idc.add_enum(-1, "{}")'.format(name))
                        enum_data = ida_typeinf.enum_type_data_t()
                        if tif.get_enum_details(enum_data):
                            for edm in enum_data:
                                m_name = edm.name
                                m_value = edm.value
                                self.emit('        idc.add_enum_member(eid, "{}", 0x{:X})'.format(
                                    m_name.replace('\\', '\\\\').replace('"', '\\"'), m_value))
                        self.emit('    except Exception as e:')
                        self.emit('        print("[-] Error creating enum {}: {{}}".format(e))'.format(name))
                        self.emit('')
        self.emit('    print("[+] Applied enums")')
        self.emit('')

    def export_types(self):
        self.emit('    # === Local Types ===')
        self.emit('    print("[*] Applying local types...")')
        self.emit('    # Note: Local types require manual export/import via File -> Produce file')
        self.emit('    # or using the Type Library manager')
        self.emit('    print("[+] Local types noted (manual step required)")')
        self.emit('')

    def export_flags(self):
        self.emit('    # === Data Type Flags ===')
        self.emit('    print("[*] Applying data type flags...")')
        self.emit('    # Note: Struct type flags at addresses are skipped')
        self.emit('    # These are typically auto-analyzed and don\'t need manual restoration')
        self.emit('    print("[+] Data type flags skipped (auto-analyzed)")')
        self.emit('')

    def export_patched_bytes(self):
        self.emit('    # === Patched Bytes ===')
        self.emit('    print("[*] Applying patched bytes...")')
        count = 0
        for seg_ea in idautils.Segments():
            seg = idaapi.getseg(seg_ea)
            if not seg:
                continue
            seg_end = idc.get_segm_end(seg_ea)
            seg_size = seg_end - seg_ea
            if seg_size <= 0:
                continue
            data = idc.get_bytes(seg_ea, seg_size)
            if data is None:
                continue
            for i in range(seg_size):
                ea = seg_ea + i
                orig = idc.get_original_byte(ea)
                curr = data[i]
                if isinstance(curr, int) and orig != curr:
                    self.emit('    idc.patch_byte(0x{:X}, 0x{:02X})'.format(ea, curr))
                    count += 1
        self.emit('    print("[+] Applied {} patched bytes")'.format(count))
        self.emit('')

def main():
    input_file = idc.get_input_file_path()
    base_name = os.path.splitext(os.path.basename(input_file))[0]
    output_dir = os.path.dirname(input_file)
    output_path = os.path.join(output_dir, "{}_exported.py".format(base_name))

    config_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.json")
    if not os.path.exists(config_path):
        config_path = os.path.join(output_dir, "config.json")

    exporter = IDBExporter(output_path, config_path)
    exporter.export()
    print("[+] Done! Run the generated script in another IDA instance to apply analysis.")

if __name__ == "__main__":
    main()